/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBox: typeof import('./src/components/base/BaseBox.vue')['default']
    ComponentTestCount: typeof import('./src/components/Tests/ComponentTestCount.vue')['default']
    'Ep:menu': typeof import('~icons/ep/menu')['default']
    'IMaterialSymbols:openInFull': typeof import('~icons/material-symbols/open-in-full')['default']
    'IMingcute:menuFill': typeof import('~icons/mingcute/menu-fill')['default']
    'IPh:hamburgerFill': typeof import('~icons/ph/hamburger-fill')['default']
    IssueList: typeof import('./src/components/IssueList.vue')['default']
    IssueListItem: typeof import('./src/components/IssueListItem.vue')['default']
    ModulesCount: typeof import('./src/components/Modules/ModulesCount.vue')['default']
    PlanFact: typeof import('./src/components/PlanFact.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablerLayoutSidebarLeftExpand: typeof import('~icons/tabler/layout-sidebar-left-expand')['default']
    TablerLayoutSidebarRightExpand: typeof import('~icons/tabler/layout-sidebar-right-expand')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
