// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormulaWidget: typeof import('./components/widgets/formulaWidget.vue')['default']
    'ICarbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconAccessibility: typeof import('~icons/ic/on-accessibility')['default']
    'IFoundation:widget': typeof import('~icons/foundation/widget')['default']
    'IUil:arrowsResize': typeof import('~icons/uil/arrows-resize')['default']
    JsonEditor: typeof import('./components/JsonEditor.vue')['default']
    README: typeof import('./components/README.md')['default']
    TestWidget: typeof import('./components/widgets/testWidget.vue')['default']
    'TestWidget copy': typeof import('./components/widgets/testWidget copy.vue')['default']
  }
}

export { }
