// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
  }
}

export { }
