/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColorWidget: typeof import('./components/widgets/ColorWidget.vue')['default']
    FillStyleWidget: typeof import('./components/widgets/FillStyleWidget.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormulaWidget: typeof import('./components/widgets/formulaWidget.vue')['default']
    IMyIconsCrossHatch: typeof import('~icons/my-icons/cross-hatch')['default']
    IMyIconsEmpty: typeof import('~icons/my-icons/empty')['default']
    IMyIconsHachure: typeof import('~icons/my-icons/hachure')['default']
    IMyIconsSolid: typeof import('~icons/my-icons/solid')['default']
    'IUil:arrowsResize': typeof import('~icons/uil/arrows-resize')['default']
    JsonEditor: typeof import('./components/JsonEditor.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestWidget: typeof import('./components/widgets/testWidget.vue')['default']
    WrapperWidget: typeof import('./components/widgets/wrapperWidget.vue')['default']
  }
}
