// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IFluentDelete24Filled: typeof import('~icons/fluent/delete24-filled')['default']
    'IMaterialSymbols:deleteRounded': typeof import('~icons/material-symbols/delete-rounded')['default']
    IMaterialSymbolsDeleteRounded: typeof import('~icons/material-symbols/delete-rounded')['default']
    Modals: typeof import('./src/components/Modals.vue')['default']
    NewDiagram: typeof import('./src/components/diagrams/NewDiagram.vue')['default']
    Query: typeof import('./src/components/Query.vue')['default']
    QueryExecutor: typeof import('./src/components/QueryExecutor.vue')['default']
    QueryResult: typeof import('./src/components/QueryResult.vue')['default']
    QueryResultType: typeof import('./src/components/QueryResultType.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
