// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarQueryResult: typeof import('./src/components/QueryResult/Bar/BarQueryResult.vue')['default']
    BarQueryResultSettings: typeof import('./src/components/QueryResult/Bar/BarQueryResultSettings.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    CoyaQueryResult: typeof import('./src/components/QueryResult/CoyaQueryResult.vue')['default']
    EChartQueryResult: typeof import('./src/components/QueryResult/EChartQueryResult.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IFluentDelete24Filled: typeof import('~icons/fluent/delete24-filled')['default']
    'IMaterialSymbols:deleteRounded': typeof import('~icons/material-symbols/delete-rounded')['default']
    IMaterialSymbolsDeleteRounded: typeof import('~icons/material-symbols/delete-rounded')['default']
    IndicatorIntervals: typeof import('./src/components/QueryResult/Indicator/Settings/IndicatorIntervals.vue')['default']
    IndicatorQueryResult: typeof import('./src/components/QueryResult/Indicator/IndicatorQueryResult.vue')['default']
    IndicatorQueryResultSettings: typeof import('./src/components/QueryResult/Indicator/IndicatorQueryResultSettings.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    Modals: typeof import('./src/components/Modals.vue')['default']
    NewDiagram: typeof import('./src/components/diagrams/NewDiagram.vue')['default']
    Query: typeof import('./src/components/Query.vue')['default']
    QueryExecutor: typeof import('./src/components/QueryExecutor.vue')['default']
    QueryResult: typeof import('./src/components/QueryResult.vue')['default']
    QueryResultLoader: typeof import('./src/components/QueryResult/QueryResultLoader.vue')['default']
    QueryResultType: typeof import('./src/components/QueryResultType.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceFSExplorer: typeof import('./src/components/Source/SourceFSExplorer.vue')['default']
    SourcePreview: typeof import('./src/components/Source/SourcePreview.vue')['default']
    SourceSourcePreview: typeof import('./src/components/Source/SourceSourcePreview.vue')['default']
    Status: typeof import('./src/components/Status.vue')['default']
  }
}
