import type { CodeInfo } from "coya-ts-analyzer";

export default <CodeInfo[]>[
  {
    "from": "/cmp.vue.ts",
    "relationType": "import",
    "to": "/util.ts",
    "type": "relationship",
  },
  {
    "entityType": "file",
    "filePath": "/cmp.vue.ts",
    "id": "/cmp.vue.ts",
    "type": "entity",
  },
  {
    "entityType": "file",
    "filePath": "/util.ts",
    "id": "/util.ts",
    "type": "entity",
  },
  {
    "from": "/cmp.vue.ts",
    "relationType": "import",
    "to": "vue",
    "type": "relationship",
  },
  {
    "entityType": "import_declaration",
    "filePath": "<unknow>",
    "id": "vue",
    "source": "<unknown>",
    "type": "entity",
  },
  {
    "entityType": "function",
    "filePath": "/cmp.vue.ts",
    "id": "/cmp.vue.ts/render",
    "source": "",
    "type": "entity",
    "typeString": "typeof import(\" / cmp.vue\").render",
  },
  {
    "entityType": "variable",
    "filePath": "<unknown>",
    "id": "/cmp.vue.ts/openBlock",
    "source": "<unknown>",
    "type": "entity",
  },
  {
    "entityType": "variable",
    "filePath": "<unknown>",
    "id": "/cmp.vue.ts/createElementBlock",
    "source": "<unknown>",
    "type": "entity",
  },
  {
    "entityType": "variable",
    "filePath": "<unknown>",
    "id": "/cmp.vue.ts/toDisplayString",
    "source": "<unknown>",
    "type": "entity",
  },
  {
    "from": "/cmp.vue.ts/render",
    "relationType": "use",
    "to": "/cmp.vue.ts/openBlock",
    "type": "relationship",
  },
  {
    "from": "/cmp.vue.ts/render",
    "relationType": "use",
    "to": "/cmp.vue.ts/createElementBlock",
    "type": "relationship",
  },
  {
    "from": "/cmp.vue.ts/render",
    "relationType": "use",
    "to": "/cmp.vue.ts/toDisplayString",
    "type": "relationship",
  },
  {
    "entityType": "function",
    "filePath": "/cmp.vue.ts",
    "id": "/cmp.vue.ts/setup",
    "source": "",
    "type": "entity",
    "typeString": "(__props: any, { expose }: { expose: any; }) => { val: any; fn1: typeof import(\" / util\").fn1; }",
  },
  {
    "entityType": "function",
    "filePath": "/util.ts",
    "id": "/util.ts/fn1",
    "source": "",
    "type": "entity",
    "typeString": "typeof import(\" / util\").fn1",
  },
  {
    "from": "/cmp.vue.ts/setup",
    "relationType": "use",
    "to": "/util.ts/fn1",
    "type": "relationship",
  },
  {
    "from": "/cmp.vue.ts/render",
    "relationType": "declaredIn",
    "to": "/cmp.vue.ts",
    "type": "relationship",
  },
  {
    "from": "/cmp.vue.ts/setup",
    "relationType": "declaredIn",
    "to": "/cmp.vue.ts",
    "type": "relationship",
  },
  {
    "from": "/util.ts/fn1",
    "relationType": "declaredIn",
    "to": "/util.ts",
    "type": "relationship",
  },
  {
    "from": "/index.ts",
    "relationType": "import",
    "to": "/cmp.vue.ts",
    "type": "relationship",
  },
  {
    "entityType": "file",
    "filePath": "/index.ts",
    "id": "/index.ts",
    "type": "entity",
  },
]
