// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    Files: typeof import('./components/Files.vue')['default']
    'Mdi:arrowRightThin': typeof import('~icons/mdi/arrow-right-thin')['default']
    'Mdi:file': typeof import('~icons/mdi/file')['default']
    'Ph:folderFill': typeof import('~icons/ph/folder-fill')['default']
    Projects: typeof import('./components/Projects.vue')['default']
  }
}

export { }
