// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Files: typeof import('./components/Files.vue')['default']
    'Mdi:arrowRightThin': typeof import('~icons/mdi/arrow-right-thin')['default']
    'Mdi:file': typeof import('~icons/mdi/file')['default']
    NewCoya: typeof import('./components/NewCoya.vue')['default']
    'Ph:folderFill': typeof import('~icons/ph/folder-fill')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
