// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./components/AppMenu/AppMenu.vue')['default']
    ArrowPalette: typeof import('./components/Palette/blocks/arrow/arrowPalette.vue')['default']
    CoyaInput: typeof import('./components/ui/coyaInput.vue')['default']
    CssWidget: typeof import('./components/NodeSetting/CssWidget.vue')['default']
    Debug: typeof import('./components/Debug/Debug.vue')['default']
    EditorComponent: typeof import('./components/editorComponent.vue')['default']
    FingerPalette: typeof import('./components/Palette/blocks/finger/fingerPalette.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HoverWrapperRect: typeof import('./components/Wrap/HoverWrapperRect.vue')['default']
    NodeActionBar: typeof import('./components/NodeSetting/NodeActionBar.vue')['default']
    NodeSetting: typeof import('./components/NodeSetting/NodeSetting.vue')['default']
    Palette: typeof import('./components/Palette/Palette.vue')['default']
    PhaseBar: typeof import('./components/Phases/Json/PhaseBar.vue')['default']
    Phases: typeof import('./components/Phases/Phases.vue')['default']
    PhasesJson: typeof import('./components/Phases/PhasesJson.vue')['default']
    RectPalette: typeof import('./components/Palette/blocks/rect/rectPalette.vue')['default']
    Test: typeof import('./components/test.vue')['default']
    WrapperRect: typeof import('./components/Wrap/WrapperRect.vue')['default']
  }
}

export { }
