// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArrowPalette: typeof import('./components/Palette/blocks/arrow/arrowPalette.vue')['default']
    CoyaInput: typeof import('./components/ui/coyaInput.vue')['default']
    EditorComponent: typeof import('./components/editorComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    'ICarbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    'ICil:rectangle': typeof import('~icons/cil/rectangle')['default']
    'IGis:flagStartB': typeof import('~icons/gis/flag-start-b')['default']
    NodeSetting: typeof import('./components/NodeSetting/NodeSetting.vue')['default']
    Palette: typeof import('./components/Palette/Palette.vue')['default']
    Phases: typeof import('./components/Phases/Phases.vue')['default']
    RectPalette: typeof import('./components/Palette/blocks/rect/rectPalette.vue')['default']
    Test: typeof import('./components/test.vue')['default']
    WrapperRect: typeof import('./components/Wrap/WrapperRect.vue')['default']
  }
}

export { }
