// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./components/AppMenu/AppMenu.vue')['default']
    ArrowPalette: typeof import('./components/Palette/blocks/arrow/arrowPalette.vue')['default']
    ArrowWrapperRect: typeof import('./components/Wrap/ArrowWrapperRect.vue')['default']
    CoyaInput: typeof import('./components/ui/coyaInput.vue')['default']
    Debug: typeof import('./components/Debug/Debug.vue')['default']
    EditorComponent: typeof import('./components/editorComponent.vue')['default']
    FingerPalette: typeof import('./components/Palette/blocks/finger/fingerPalette.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    'ICarbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    'ICil:rectangle': typeof import('~icons/cil/rectangle')['default']
    'ICodicon:debug': typeof import('~icons/codicon/debug')['default']
    'IGis:flagStartB': typeof import('~icons/gis/flag-start-b')['default']
    'IGrommetIcons:documentConfig': typeof import('~icons/grommet-icons/document-config')['default']
    'IIc:baselineMouse': typeof import('~icons/ic/baseline-mouse')['default']
    'IIc:roundPlayArrow': typeof import('~icons/ic/round-play-arrow')['default']
    'IIconParkOutline:zoom': typeof import('~icons/icon-park-outline/zoom')['default']
    'ILs:underscore': typeof import('~icons/ls/underscore')['default']
    'IMdi:arrowRightThin': typeof import('~icons/mdi/arrow-right-thin')['default']
    'IMdi:arrowTopLeftThin': typeof import('~icons/mdi/arrow-top-left-thin')['default']
    'IMdi:familyTree': typeof import('~icons/mdi/family-tree')['default']
    'IMdi:motionPlayOutline': typeof import('~icons/mdi/motion-play-outline')['default']
    'IMdi:playBox': typeof import('~icons/mdi/play-box')['default']
    'IPh:rectangleBold': typeof import('~icons/ph/rectangle-bold')['default']
    'ITabler:handFinger': typeof import('~icons/tabler/hand-finger')['default']
    NodeSetting: typeof import('./components/NodeSetting/NodeSetting.vue')['default']
    Palette: typeof import('./components/Palette/Palette.vue')['default']
    PhaseBar: typeof import('./components/Phases/Json/PhaseBar.vue')['default']
    Phases: typeof import('./components/Phases/Phases.vue')['default']
    PhasesJson: typeof import('./components/Phases/PhasesJson.vue')['default']
    RectPalette: typeof import('./components/Palette/blocks/rect/rectPalette.vue')['default']
    Test: typeof import('./components/test.vue')['default']
    WrapperRect: typeof import('./components/Wrap/WrapperRect.vue')['default']
  }
}

export { }
