// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DemoCoyas: typeof import('./components/DemoCoyas.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'Mdi:arrowLeftBoldBoxOutline': typeof import('~icons/mdi/arrow-left-bold-box-outline')['default']
    'Mdi:arrowRightThin': typeof import('~icons/mdi/arrow-right-thin')['default']
    'Ph:folderFill': typeof import('~icons/ph/folder-fill')['default']
  }
}

export { }
