import SVGPathCommander from 'svg-path-commander';
export * from './setValueByPath';
export * from './whatChanged';
export * from './deepAssign';
export * from './deepCopy';
export * from './fastDeepEqual';
export * from './isNotNullOrUndefined';
export * from './isNullOrUndefined';
export * from './hexToRgba';
export * from './groupBy';
export const svgPathCommander = SVGPathCommander;
